# Generated by Django 5.0.2 on 2024-02-24 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecognizerLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="images/")),
                ("upload_dates", models.DateField(default=django.utils.timezone.now)),
                ("predictions", models.CharField(max_length=255)),
            ],
        ),
    ]
