# Generated by Django 5.0.2 on 2024-02-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recognize", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecognizerLogs",
            new_name="RecognizerLog",
        ),
    ]
