# Generated by Django 5.0.2 on 2024-03-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recognize", "0002_rename_recognizerlogs_recognizerlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recognizerlog",
            old_name="images",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="recognizerlog",
            old_name="predictions",
            new_name="prediction",
        ),
        migrations.RenameField(
            model_name="recognizerlog",
            old_name="upload_dates",
            new_name="upload_time",
        ),
    ]
