# Generated by Django 5.0.2 on 2024-03-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognize", "0003_rename_images_recognizerlog_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognizerlog",
            name="correct",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="recognizerlog",
            name="real",
            field=models.CharField(default="Null", max_length=255),
        ),
    ]
