databases:
  - name: cats-or-dogs-recognizer-db
    plan: free
    databaseName: cats-or-dogs-recognizer
    user: cats-or-dogs-recognizer

services:
  - type: web
    plan: free
    name: cats-or-dogs-recognizer
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn main.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cats-or-dogs-recognizer-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
