databases:
  - name: maindb
    plan: free
    databaseName: main
    user: main

services:
  - type: web
    plan: free
    name: cats_or_dogs_recognizer
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn main.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maindb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
