databases:
  - name: recognizerdb
    plan: free
    databaseName: recognizer
    user: recognizer

services:
  - type: web
    plan: free
    name: recognizer
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn recognizer.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recognizerdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
